cpi: google
properties:
  instances: 1
  networks:
  - name: default
    static_ip: ((bats_static_ip))
    subnets:
    - cloud_properties:
        ephemeral_external_ip: true
        network_name: ((network))
        subnetwork_name: ((subnetwork))
        tags: ((tags))
      gateway: ((internal_gw))
      range: ((internal_cidr))
      static: ((reserved_range))
    type: manual
  static_ips: ((bats_static_ip_pair))
  stemcell:
    name: hope
    version: latest
  vip: ((bats_external_ip))
  zone: ((zone))
